### ISSUE TITLE
Velas CLI install instructions for Linux doesn't work

### ISSUE THREAD

**Issue by lodembeep** [velas/velas-chain#141]
#### Problem
There seems to be an issue with the instructions on the Velas website, for reference : https://docs.velas.com/cli/install-velas-cli-tools/#for-linux

The following command :
`curl -sSf https://github.com/velas/velas-chain/releases/latest/download/velas-install-init-x86_64-unknown-linux-gnu | sh -s - LATEST_VELAS_RELEASE_VERSION`

Returns the following error :
`sh: 1: Syntax error: redirection unexpected`

#### Proposed Solution
The install command shall be updated

**Comment by vldm** [comment]
Thanks for your ticket, we will fix it soon.

**Comment by vldm** [comment]
Fixed
