### ISSUE TITLE
Make velas install update work from github releases.

### ISSUE THREAD

**Issue by vldm** [velas/velas-chain#175]
#### Problem
Cureently it searches for update from site, but we actually can find releases in github.

**Comment by Tirka** [comment]
Install tool designed to support 3 different release channels:
- stable
- beta
- edge

Which ones do we plan to maintain?


We must determine how we could tell apart releases by different channels. We can manage that either by:
- using `prerelease` checkmark
- using some kind of `tag` naming convention

**Comment by vldm** [comment]
Closed in: #192
