### ISSUE TITLE
Hi I’ve deposited USDT to buy Velas token but I cant

### ISSUE THREAD

**Issue by tejpalaux** [velas/velas-chain#195]
#### Problem
I deposited USDT to buy Velas coin but I can’t can someone please help

#### Proposed Solution
If I can’t buy Velas coin I would like to withdraw my coin .

**Comment by JayLumen** [comment]
> #### Problem
> I deposited USDT to buy Velas coin but I can’t can someone please help
> 
> #### Proposed Solution
> If I can’t buy Velas coin I would like to withdraw my coin .
hello, you already have the ticket, please comment there, we'll close this issue here
