### ISSUE TITLE
bridge transaction has been pending

### ISSUE THREAD

**Issue by vmopbz** [velas/velas-chain#219]
#### Problem
Hi I am trying to bridge my velaspad from metamask etherium mainnet to the velas network so that I can stake them

#### Proposed Solution
can this be checked and seen what is causing the issue?

**Comment by vldm** [comment]
Hi, can you add more details?
What is your workflow? Currently velas didn't **implement mempool, so transaction should not be pending**.

We are working on implementing interface similar to mempool in ethereum. But it wasn't released yet.

**Comment by vmopbz** [comment]
Hi Vladimir,

I was using the bridge to to take my velaspad from etherium chain in metamask to the vela’s chain.

This finally completed but it took a really long time. I started the process yesterday and by this morning it was complete and my tokens where on the vela’s chain.

Now I am trying to stake them and again it’s taking analogy long time. It has been stuck at the Pre-authorisation required transaction 1 of 2 for about 4 hours. 

Is there anything you want me to check to see what’s causing this delay?

Regards
Philip

**Comment by vldm** [comment]
Okay, i got you!
The core velas team is only corresponding for blockchain and tooling related to blockchain.

Looks like your problem related to velaspad.io. This is a separate project with its own team.
I don't see any infrastructure problems that may cause delays on our side.
Try to write them a mail if you any problem with their product remains.
