### ISSUE TITLE
Provide API support to auto-approve on trusted sites

### ISSUE THREAD

**Issue by McoreD** [velas/velas-chain#233]
#### Problem

Currently MetaMask requires the Confirm button being pressed by the user for approving tx. During a manual compounding operation, this requires a lot more clicks than what's required in an automated solution. 

#### Proposed Solution

Similar to Solana, in Sollet or Phatom, with the support for auto-approve, supported wallets could implement this feature.

**Comment by vldm** [comment]
Sorry metamask is not our product, we can't make auto approve fro you.
In ETHEREUM world it's okay to confirm all your transactions separately.

**Comment by McoreD** [comment]
Thanks for the response. 
Would you have your own product that's an Edge/Chrome extension which would have auto-approve?
