### ISSUE TITLE
Funds from Transfer are not in Metamask

### ISSUE THREAD

**Issue by marvin305** [velas/velas-chain#238]
#### Problem: I connected to the velas bridge to transfer VLXPAD to my Velas Network and the funds where taken out of my Binance Smart Chain network and I can also see the transaction on the Velas block explorer but my funds are not in my metamask Velas Network Wallet.

https://evmexplorer.velas.com/tx/0x1d08ad19841f391dd5cdab227ed4d0a42493cf4f6ae9bf1cb26f95182bfddb8a/token-transfers

![Screen Shot 2021-11-15 at 8 03 36 PM](https://user-images.githubusercontent.com/34537335/141876935-a91bce11-2cde-4c5a-89c3-cb205246e15c.png)
![Screen Shot 2021-11-15 at 8 04 13 PM](https://user-images.githubusercontent.com/34537335/141876978-26665474-4b10-4496-9a05-99e50d357f3e.png)

**Comment by vldm** [comment]
Please send your issue to our supports at telegram or email.
