### ISSUE TITLE
Funds (BUSD) not got transferred to my Metamask.

### ISSUE THREAD

**Issue by salomonthumma** [velas/velas-chain#239]
#### Problem
I have transferred My BUSD from velas wallet to metamask but i have not received my funds credited to my metamask wallet. 
please help me with this thank you, your help is highly appreciated.

here is the link. 
 
https://evmexplorer.velas.com/tx/0x42ff438d033b6b4e1eb71a383c57fdf3f4d0656712d8d6344033e86adc102c20/token-transfers

#### Proposed Solution

please credit funds to my BSC wallet - 0xA7576aeE004DD4eba8109Dd1DF8BaE04Bce20d03

**Comment by vldm** [comment]
Please send your issue to our supports at telegram or email.
