### ISSUE TITLE
 Transaction confirmed at 10:40 on 11/18/2021. but I didnt recieved USDT. Gateio not support Vales Chain

### ISSUE THREAD

**Issue by Ahomir** [velas/velas-chain#241]
Hello. I sent usdt, from my metamask wallet to my Gate account but I think I sent wrong way. 
Can you help me about this situation.

![image](https://user-images.githubusercontent.com/94600265/142376753-97b8443b-6ef5-4cb2-a351-8e433fcd047a.png)

0xbc651353e1bfda9228dde5f0f94643894ac3e6bcffe5e520b3f896f6aec3e7eb

**Comment by Ahomir** [comment]
![image](https://user-images.githubusercontent.com/94600265/142425609-d60a4fce-c45b-420d-9587-a6a01917816f.png)

**Comment by vldm** [comment]
Sorry github issue is about code bugs or proposals. Can you go to the velas support in telegram, and ask your question?
