### ISSUE TITLE
velas in windows does not work !!

### ISSUE THREAD

**Issue by Jamill-hallak** [velas/velas-chain#281]
#### Problem
after following the doc for installation I face this problem with "velas-install-init.exe"
with massage " this file is corrupted or unreadable

**Comment by Tirka** [comment]
Sorry for the delayed answer. We found an error in our documentation. Here is an updated `velas-cli` installation guide:

- Open a Command Prompt (`cmd.exe`) as an Administrator

  - Search for Command Prompt in the Windows search bar. When the Command
    Prompt app appears, right-click and select “Open as Administrator”.
    If you are prompted by a pop-up window asking “Do you want to allow this app to
    make changes to your device?”, click Yes.

- Copy and paste the following command, then press Enter to download the Velas
  installer into a temporary directory:

```bash
curl -L https://github.com/velas/velas-chain/releases/download/v0.5.1/velas-install-init-x86_64-pc-windows-msvc.exe --output C:\velas-install-tmp\velas-install-init.exe --create-dirs
```

- Copy and paste the following command, then press Enter to install the latest
  stable version of Velas. If you see a security pop-up by your system, please 
  select to allow the program to run.

```bash
C:\velas-install-tmp\velas-install-init.exe stable
```

- When the installer is finished, press Enter.

- Close the command prompt window and re-open a new command prompt window as a
  normal user
  - Search for "Command Prompt" in the search bar, then left click on the
    Command Prompt app icon, no need to run as Administrator)
- Confirm you have the desired version of `velas` installed by entering:

```bash
velas --version
```

- After a successful install, `velas-install update` may be used to easily
  update the Velas software to a newer version at any time.
