### ISSUE TITLE
How to get balance for native VLX addresses using explorer.velas.com/api ?

### ISSUE THREAD

**Issue by c0dehunter** [velas/velas-chain#300]
A lot of our users want Velas native added to our portfolio tracker in The Crypto App. The issue is that we are unable to find an API endpoint which would return balance of a native VLX address. 

For legacy it's no problem, it works well:
https://explorer.velas.com/api?module=account&action=balance&address=V9oBro5LPNsqU6sVi5p4ZHUK2CDxLJf4U9

Response:
```
{
"message": "OK",
"result": "100008538810000000000", // 100.00853881 VLX
"status": "1"
}
```

But it doesn't work for native VLX:
https://explorer.velas.com/api?module=account&action=balance&address=AJEswYAPthrCquVfUGc8jZJDfhiieDw5W7addmgGmQQN

Response:
```
{
"message": "Invalid address hash",
"result": null,
"status": "0"
}
```

The above address has 49.9 VLX according to native.velas.com explorer: https://native.velas.com/address/AJEswYAPthrCquVfUGc8jZJDfhiieDw5W7addmgGmQQN

**Comment by Tirka** [comment]
You can use RPC `getBalance` for that purpose.

Here is an cURL balance request sample for address `AJEswYAPthrCquVfUGc8jZJDfhiieDw5W7addmgGmQQN`:
```curl
curl --location --request POST 'https://api.mainnet.velas.com' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0",
    "method":"getBalance",
    "params":["AJEswYAPthrCquVfUGc8jZJDfhiieDw5W7addmgGmQQN"],
    "id":1
}'
```

Sample JSON response:
```json
{
    "jsonrpc": "2.0",
    "result": {
        "context": {
            "slot": 80014181
        },
        "value": 48263366310
    },
    "id": 1
}
```
