### ISSUE TITLE
how to get 32byte native_recipient address ?

### ISSUE THREAD

**Issue by mikewang68** [velas/velas-chain#446]
#### Problem

when  i use metamask managment wallet , i want to transfer token from metamask to native by using remix programming , document say call interface TransferToNative ,  but velas account is 44byte , not 32byte

pragma solidity ^0.6.0;

interface TransferToNative {
  function transferToNative(bytes32 native_recipient) virtual external payable;
}

**Comment by vldm** [comment]
You can convert native address from base58 to hex
